### ISSUE TITLE
flacko - Curator can inflate fee right before accepting an invitation for an auction

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#111]
flacko

medium

# Curator can inflate fee right before accepting an invitation for an auction

## Summary
A curator can inflate their fee to a higher one than promoted to an auction's seller right before accepting the invitation to curate the auction and thus charging the seller more and incurring unexpected costs for them.
## Vulnerability Detail
> In the contest's README there is no mention of the Curator role, so it is to be considered RESTRICTED.

When a seller is creating an auction, they specify the address of the curator of their auction once and for all.

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/Auctioneer.sol#L215C1-L220C10
```solidity
        // Store curation information
        {
            FeeData storage fees = lotFees[lotId];
            fees.curator = routing_.curator;
            fees.curated = false;
        }
```

From then on the only possible action involving the curator is for them to accept the invitation. They can neither be replaced, nor removed. The curator on the other side is allowed to accept the invitation at any point in time before the lot ends and the curator fee for the lot is set to the current fee the curator has set for themselves at the time of acceptance.

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L646C1-L652C101
```solidity
        if (feeData.curated || module.hasEnded(lotId_) == true) revert InvalidState();

        Routing storage routing = lotRouting[lotId_];

        // Set the curator as approved
        feeData.curated = true;
        feeData.curatorFee = fees[keycodeFromVeecode(routing.auctionReference)].curator[msg.sender];
```

The curator sets their fee by calling `setCuratorFee()` on the auction house:

https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/FeeManager.sol#L110C1-L116C6
```solidity
    function setCuratorFee(Keycode auctionType_, uint48 fee_) external {
        // Check that the fee is less than the maximum
        if (fee_ > fees[auctionType_].maxCuratorFee) revert InvalidFee();

        // Set the fee for the sender
        fees[auctionType_].curator[msg.sender] = fee_;
    }
```

As can be seen, the only thing mitigating the damage the curator can do is the `maxCuratorFee` that the protocol itself sets, but that wouldn't do much as this is a global limit and some curators might charge more, others less and if the protocol is to welcome the ones that charge more that would mean they have to set a higher `maxCuratorFee` that curators with bad intentions can take advantage of.

## Impact
A proposed curator can set their fee to the maximum right before accepting an invitation to curate an auction and thus incur an extra expense for the lot seller. The seller themselves have almost non-existent means to tackle a malicious curator as their only option is to cancel the auction they've set this curator to and this is only an option before the lot has started. After the lot starts the curator is guaranteed to get their fees. For fixed price auctions (atomic) that is every time a buyer calls `purchase()` and for marginal price auctions (batch) that is at `settle()`ment of the auction.

## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/AuctionHouse.sol#L634-L699

## Tool used
Manual Review

## Recommendation
The safety measure I'd recommend for this issue are:
- Allow the curator to only accept their invitation before the lot has started
- Allow the seller of a lot to remove a curator as such from the lot
- Record the curator fee for the lot at the time of creating the lot

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Axis-Fi/moonraker/pull/140

**Comment by AtanasDimulski** [comment]
Escalate,

This issue shares the same root cause and impact as [#183](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/183) as per my [comment](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/183#issuecomment-2048001265) . This issue as well should be considered as low, as there is no direct loss of funds or breaking core contract functionality

**Comment by sherlock-admin2** [comment]
> Escalate,
> 
> This issue shares the same root cause and impact as [#183](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/183) as per my [comment](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/183#issuecomment-2048001265) . This issue as well should be considered as low, as there is no direct loss of funds or breaking core contract functionality

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by flackoon** [comment]
@AtanasDimulski The root cause of https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/183 has nothing to do with the root cause of this issue. The other submission is that even after lowering the global `maxCuratorFee`, a curator that once has set their fee to the old max can still accept invitations to curate lots and their 'old max fee' would still be applied to auctions created after the `maxCuratorFee` being lowered.

This issue is about the curator inflating their fee to the maximum allowed right before accepting an invitation and the lot seller not being able to do anything about it after a lot has started.
> There is no direct loss of funds

In my opinion, the loss is quite direct as the seller is left with the only option to pay the curator fee once the lot has started.

Also I've stated quite clearly in my report that:
> In the contest's README there is no mention of the Curator role, so it is to be considered RESTRICTED.

This issue has nothing to do with user input validation (as you've stated in your [comment](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/183#issuecomment-2048001265) - "a case can be made that setting a curator who is willing to try and scam the auction creator is a user mistake and as per sherlock rules User input validation to prevent user mistakes is not considered a valid issue.") but rather with trust assumptions about the curator role. A seller can still input a valid address of a curator upon lot creation, but there's no guarantee that the curator will act honestly and will not bump their fee above what both parties have agreed upon earlier.

**Comment by AtanasDimulski** [comment]
@flackoon the root of the issue in my understanding is the admin of the protocol setting a certain fee, and then lowering it, where the checks are made is not of significant importance. As I have addressed in my first point I believe this should be considered as an admin mistake. As for the trust assumptions I am not implying that the auction creator will set address(0) as a parameter but an address of someone whom they trust and have a prior agreement with. The curator role is not a role given by the protocol, so it shouldn't be viewed the same way as if an admin role is trusted or not. I strongly believe this is a low issue, as it requires parameters controlled by the admin to be set in a certain order. I have nothing more to add and will let @nevillehuang  and @Czar102 have a look.

**Comment by kazantseff** [comment]
While I agree with @AtanasDimulski, that the issue should be considered as low, I think that the reasons for this are different from those stated here. The variable `maxCuratorFee` is known in advance to every seller wishing to utilize curators for their auctions. If the seller willingly proposes a curator, knowing that he can pay up to the `maxCuratorFee` **and** still goes with it, it can only mean that the seller accepts the fact, that at worst he will pay that max fee allowed by the protocol. There is no inconsistency since every seller operates under the same conditions and expectations that maximum fees might be charged. Additionally, I also think that the argument of a "malicious curator" cannot be applied here, as setting the curator is solely a seller's discretion, so it should be considered a user mistake.

**Comment by nevillehuang** [comment]
Adding my argument here already shared from discord, I also agree with @flackoon comment regarding duplication with #183 

> Curators are not trusted completely by sellers, and this behavior is not indicated as intended behavior. This encourages ALL curators to charge maximum fees to all sellers which is clear inconsistency to me

**Comment by Evert0x** [comment]
@nevillehuang did the protocol team write somewhere about the trust levels of the curator role?

**Comment by nevillehuang** [comment]
@Evert0x The only trusted protocol role is the protocol owner

> The only role for the protocol is the AuctionHouse owner. They can install new modules and upgrade existing modules (Auctions or Derivatives) in the AuctionHouse, set fee values, set the address that protocol fees accrue to, and set configuration parameters on the modules.

All other roles are permisionless, so it is implied that each role shouldn't have additional advantages over others

**Comment by AtanasDimulski** [comment]
> @Evert0x The only trusted protocol role is the protocol owner
> 
> > The only role for the protocol is the AuctionHouse owner. They can install new modules and upgrade existing modules (Auctions or Derivatives) in the AuctionHouse, set fee values, set the address that protocol fees accrue to, and set configuration parameters on the modules.
> 
> All other roles are permisionless, so it is implied that each role shouldn't have additional advantages over others

The curator role is not a role that is set by the protocol, it is set by the person creating the auction. Also, I want to point out that an admin of the protocol which is a trusted role, has to first set a higher fee and then set a lower fee in order for this issue to be even possible. Per sherlock rules this is not a valid issue. 


**Admin Input/call validation:** Protocol admin is considered to be trusted in most cases, hence issues where

1. Admin incorrectly enters an input parameter. Example: Make sure interestPerMin > 1 ether as it is an important parameter. This is not a valid issue.

2. Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue.

3. An admin action can break certain assumptions about the functioning of the code. Example: Pausing a collateral causes some users to be unfairly liquidated or any other action causing loss of funds. This is not considered a valid issue.

**Comment by nevillehuang** [comment]
@AtanasDimulski I think your second point is not relevant to this discussion, given the maximum fee is simply a global limit set by the admin. It comes down to whether or not seller trusts curator. I just don't see the point of having a variable curator fee when every single curator is incentivized to charge the maximum towards sellers

> As can be seen, the only thing mitigating the damage the curator can do is the maxCuratorFee that the protocol itself sets, but that wouldn't do much as this is a global limit and some curators might charge more, others less and if the protocol is to welcome the ones that charge more that would mean they have to set a higher maxCuratorFee that curators with bad intentions can take advantage of.

**Comment by AtanasDimulski** [comment]
> @AtanasDimulski I think your second point is not relevant to this discussion, given the maximum fee is simply a global limit set by the admin. It comes down to whether or not seller trusts curator. I just don't see the point of having a variable curator fee when every single curator is incentivized to charge the maximum towards sellers
> 
> > As can be seen, the only thing mitigating the damage the curator can do is the maxCuratorFee that the protocol itself sets, but that wouldn't do much as this is a global limit and some curators might charge more, others less and if the protocol is to welcome the ones that charge more that would mean they have to set a higher maxCuratorFee that curators with bad intentions can take advantage of.

Yes I agree, for some reason I thought frontrunning was part of the issue. However, this [comment](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/111#issuecomment-2048226097) by @kazantseff 
 clearly describes why this is not a medium issue. And what you are proposing is a design improvement, which again is not a valid issue per sherlock rules.

**Comment by flackoon** [comment]
If we extrapolate @kazantseff's point a bit
>If the seller willingly proposes a curator, knowing that he can pay up to the maxCuratorFee and still goes with it, it can only mean that the seller accepts the fact, that at worst he will pay that max fee allowed by the protocol.

we might as well stop using slippage protection in swaps on decentralized exchanges because it's expected some slippage to occur anyway, no matter how bad, no?

On the other hand, the issue we have here can be very simply mitigated by setting the `curatorFee` of a lot at the time of the lot creation (instead of at accepting an invitation for curating it) so that the curator has no control over the fee after the lot creation and so that the seller can be sure what fee they are going to be paying at the end of the day. I personally wouldn't call that a design improvement.

**Comment by nevillehuang** [comment]
I don't see this as a design improvement either, unless noted in contest details/documentation/code comments that it is intended behavior fees can always and should be set to the maximum and/or sellers should trust curators, I see a clear inconsistency where curators can abuse their fee setting power. Lets leave it to @Evert0x to decide interpretation, but the protocol fixing this seems to indicate this is not expected behavior (although not relevant).

**Comment by kazantseff** [comment]
@flackoon, I think that the slippage comparison is not accurate in this case. Yes, the maxCuratorFee is expected value, but unlike the slippage, this value is set by an admin before the curation begins, and because it is set by a trusted admin we can assume that it will be of a reasonable scale, unlike the slippage, which can be up to a 100%.

Additionally, I think that there is no need to trust a curator, since he is limited in his actions by an admin who sets the value for the maxCuratorFee. It definitely would've been a problem if there was a way to inflate the fee way above the max allowed, but from the protocol standpoint the max fee invariant is enforced and cannot be broken by a malicious curator.

**Comment by 10xhash** [comment]
> The protocol team fixed this issue in the following PRs/commits: [Axis-Fi/moonraker#140](https://github.com/Axis-Fi/moonraker/pull/140)

Fixed
The fees are cached at the time of auction creation

**Comment by sherlock-admin4** [comment]
The Lead Senior Watson signed off on the fix.

**Comment by Evert0x** [comment]
I believe the curator is restricted by the admin through the `maxCuratorFee` variable. I understand that this fee is basically  the default fee as it maximizes profits for the curator.

Planning to accept escalation and invalidate issue

**Comment by flackoon** [comment]
If the admin was to restrict every single curator individually through `maxCuratorFee` that'd mean they have to change the variable's value every time a curator goes out and calls `setCuratorFee()`, which is highly impractical imo. The way I believe it's intended to work is - an admin sets the `maxCuratorFee` once to a sensible value and occasionally (if at all) changes it. And as I've outlined in my report, if the protocol is to welcome curators who charge a higher fee they have to set a higher `maxCuratorFee` which less prominent curators can take advantage of. I really don't see it working any other way as the protocol would have to otherwise monitor calls to `setCuratorFee()` and regularly adjust the maximum fee allowed and there's still no guarantee that while they've upped the maximum fee so that a given curator sets their fee, a less prominent curator who usually charges a lower fee wouldn't come in and again take advantage of that.

**Comment by nevillehuang** [comment]
@Oighty @0xJem Is this really intended behavior? Why would you not use a constant curator fee and instead implement a max restriction if the claims here by head of judging and other watsons are correct? 

Anyhows I will respect whatever decision head of judging makes, since they have final say anyways.

**Comment by DanielNedelchev** [comment]
this should be a valid issue in my opinion , Curator is chosen by the auction seller 
Example :
max curator fee is 10%
curator advertise low fee for curating like 2% gets chosen by auction seller , before the lot is started the curator bumps to 10%
frauding the auction seller , as neville said why not use just a constant fee for every auction instead ? 
the only way in this current state to prevent auction seller getting played by curator and  is to monitor every single lot and restrict manually the maxcurator fee that is impractical to say the least .

**Comment by DanielNedelchev** [comment]
> > The protocol team fixed this issue in the following PRs/commits: [Axis-Fi/moonraker#140](https://github.com/Axis-Fi/moonraker/pull/140)
> 
> Fixed The fees are cached at the time of auction creation

and they got fixed as per recommended in the report , i cant see why this is not a valid issue .

**Comment by AtanasDimulski** [comment]
> this should be a valid issue in my opinion , Curator is chosen by the auction seller Example : max curator fee is 10% curator advertise low fee for curating like 2% gets chosen by auction seller , before the lot is started the curator bumps to 10% frauding the auction seller , as neville said why not use just a constant fee for every auction instead ? the only way in this current state to prevent auction seller getting played by curator and is to monitor every single lot and restrict manually the maxcurator fee that is impractical to say the least .

What you are describing is exactly what @Evert0x said that the ``maxCuratorFee`` can't be bypassed by the curator - so no vulnerability there. And your suggestions are design improvements, whether this is the optimal way for the protocol to operate is not the question. Design improvements are not accepted per Sherlock rules. The auction creator knows in advance what the max curator fee is, so if he chooses a curator that will use the maximum fee this is clearly a user mistake. No matter how you try to spin it, this issue doesn't fall into a valid issue category per Sherlock rules. As for the protocol fixing the issue, this has absolutely nothing to do with the validity of the issue.

**Comment by DanielNedelchev** [comment]
u were talking about frontrunning a few comments back you are the guy trying to spin up stories under people's reports trying to invalide them and this is not your first time doing this so u can get a bigger chunk of the reward pool  , this is why sherlock is getting avoided by other security researchers , dont u have anything better to do ? like doing ur job better not going around on other people reports trying to put them down so u get an extra $ , there i said it .

**Comment by AtanasDimulski** [comment]
> u were talking about frontrunning a few comments back you are the guy trying to spin up stories under people's reports trying to invalide them and this is not your first time doing this so u can get a bigger chunk of the reward pool , this is why sherlock is getting avoided by other security researchers , dont u have anything better to do ? like doing ur job better not going around on other people reports trying to put them down so u get an extra $ , there i said it .

Thanks for your opinion, I have never hidden the fact of why I escalate issues.  However every issue that I escalated I have a valid reason for. If you read all the comments you will see that I have admitted I have made a mistake about the frontrunning part but this even makes the issue less plausible as I have stated. Carefully read the code, go through Sherlock rules, try to put your feelings aside, and try to be fair and objective going forward.

**Comment by DanielNedelchev** [comment]
I have no finger in this issue to be emotional  , i just dont like your practice , not very colleague-like behavior thats all .

**Comment by Evert0x** [comment]
> @Oighty @0xJem Is this really intended behavior? Why would you not use a constant curator fee and instead implement a max restriction if the claims here by head of judging and other watsons are correct?
> 
> Anyhows I will respect whatever decision head of judging makes, since they have final say anyways.

Please show me docs/readme/code that describes the intention, the current opinion of the protocol team holds little value. 

Still planning to accept escalation and invalidate issue

**Comment by nevillehuang** [comment]
@Evert0x Apologies for the subjective comment. After further research, I agree that this issue can be invalidated since the code comments and documentation does not indicate clearly the intention of the curator fee setting to maximum.

[Here](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/bases/FeeManager.sol#L22) it is stated that:

```
    /// @notice     Curator fees are taken in the payoutToken and are sent when the auction is settled / purchase is made. Curators can set these up to the configured maximum.
```

So as long as before the auction is settled/purchase is made, it can be reconfigured, so this indicates to me it is intended behavior.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/111/#issuecomment-2048005897): accepted
