### ISSUE TITLE
Kose - Auction Can Be Locked with It's Funds in Decryption Phase in Mainnet Because Massive Gas Payment is Required From Users

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#117]
Kose

medium

# Auction Can Be Locked with It's Funds in Decryption Phase in Mainnet Because Massive Gas Payment is Required From Users

## Summary
The decryption process in the EMPA module presents a significant issue as it demands a massive amount of gas, potentially locking funds within the contract. With the burden of gas costs falling on auction participants (they are the ones that expected to decrypt the auction), there is little to no incentive to complete the decryption process in the mainnet, leading to funds being trapped within the contract.
## Vulnerability Detail
Upon conclusion of a sealed bid batch auction, the settlement process initiates with decryption. It is expected that users will call the decrypt function within the EMPA module, and only after all decryption operations are completed can the settlement proceed.This decryption task is undertaken by users of the protocol without any incentives, except for the incentive to be able to retrieve their amount back if the auction is stuck in the decryption phase, which actually can not be counted as an "incentive".

Decryption process is very expensive in terms of gas such that it doesn't have to be done in one transaction because it can exceed gas limit of a block. This is also documented by protocol in *[design/EMPA.md](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/design/EMPA.md#auction-settlement-part-1-decryption)* as follows:
>    It may take several decryption transactions depending on the number of bids and gas limit. Once, all bids are decrypted on the contract, we can move to part 2 of the settlement process.

While such costs might be acceptable for Layer 2's, they present a serious challenge for mainnet operations. As demonstrated in the provided POC below, even with an auction which has 100 bids in total, the gas cost for decryption escalates to 7 million. Considering the mean gas price in February 2024, which is 40 gwei, and an ETH price of $3500, this translates to nearly $1,000 in gas costs for decryption.

If we consider auctions that have more bids we can reach to more catastrophic scenarios. Here is a demonstration:
Add following test to *test/modules/auctions/EMPA/settle.t.sol*. Modifier **givenLargeNumberOfUnfilledBids** is created by protocol and it has 1510 total bids in it. You can adjust the number of bids in that modifier to test different bid amounts.
```solidity
     function test_largeNumberOfUnfilledBids_gasUsageOfDecryption()
        external
        givenLotIsCreated
        givenLotHasStarted
        givenLargeNumberOfUnfilledBids
        givenLotHasConcluded
        givenPrivateKeyIsSubmitted
    {
        EncryptedMarginalPriceAuctionModule.AuctionData memory auctionData = _getAuctionData(_lotId);
        uint256 gasBefore = gasleft();
        _module.decryptAndSortBids(_lotId, auctionData.nextBidId - 1);
        uint256 gasAfter = gasleft();

        console2.log(gasBefore - gasAfter);
    }
```
Output:
>  [PASS] test_largeNumberOfUnfilledBids_gasUsageOfDecryption() (gas: 321856062)
Logs:
  101789276

In this scenario which has 1510 bids, the gas cost of decryption reached 101 million, hence it needs to be decrypted in at least 4 blocks. The cost of this decryption with 40 gwei gas price is = $14_000 (imagine it during a bullish market season). 

Failure to cover this decryption cost would result in all funds being trapped within the contract. Since there is no way to change the state of the auction once it has concluded, except through decryption, funds cannot be moved. This is an amount that cannot be reasonably expected from users to provide, thus leading to the likelihood of numerous auctions becoming stuck in the decryption phase on the mainnet.

One side note is that settle() process that comes after decryption also is a process that is costly in terms of gas. It worth nearly 1/4 of decryption process. Since decryption phase is costly enough to cause an issue, I didn't go into details of settle() process and it's gas costs in submission.
## Impact
Funds belonging to both buyers and sellers will remain trapped within the contract unless someone is willing to pay for a rescue operation. The possibility of a rescue scenario can only be anticipated within auctions where an individual has placed a high-value bid, or it may be expected from the seller. However, in both cases, these users stand to lose a significant amount of funds during the decryption process.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/modules/auctions/EMPAM.sol/#L441
## Tool used

Manual Review

## Recommendation
It would be unfair to suggest changing the decryption process, as it is one of the main functionalities of the system and is necessary for the sealed bid batch auction to function properly. Additionally, limiting bid amounts would not resolve the issue. Therefore, the only feasible solution that comes to mind without requiring extensive changes to the codebase is to refrain from using the mainnet for the EMPA module.

**Comment by Oighty** [comment]
Acknowledge decryption and settlement can be expensive. I'm not sure this is an issue as much as a good heads up (and understanding of the system). We are not planning to deploy this module to mainnet initially, but I don't think I put that in the contest notes. However, we are doing a couple things to mitigate this in general:
1. Working on a more optimized queue implementation that doesn't brick decrypt or settle on so few bids
2. Due to some of the other "funds stuck" issues, changing the rules on claiming refunds so that a user doesn't get stuck.
3. Preventing non-gas stuck issues, such as blacklist reverting a major step.

**Comment by AtanasDimulski** [comment]
Escalate,

This is a gas optimization issue and the protocol has specifically added a functionality to decrypt the bids on batches (so it never leads to DOS) - sherlock has never accepted gas optimization issues, and it will be unfair to start doing it now. Considering [Gas optimizations](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid) is the first category of issues that are not considered valid. Although the first section of the escalation should be more than enough to invalidate this issue I have added some additional remarks. The protocol can be deployed on L2(and most probably will be),  and if it is to be deployed on mainnet, the auction creator has the ability to set a min bid percent, so he can avoid having a lot of bids if he set it at 10%, and thus the incentives for someone to call the decrypt function are there as well as much lower gas consumed, due to the number of bids.

**Comment by sherlock-admin2** [comment]
> Escalate,
> 
> This is a gas optimization issue and the protocol has specifically added a functionality to decrypt the bids on batches (so it never leads to DOS) - sherlock has never accepted gas optimization issues, and it will be unfair to start doing it now. Considering [Gas optimizations](https://docs.sherlock.xyz/audits/judging/judging#vii.-list-of-issue-categories-that-are-not-considered-valid) is the first category of issues that are not considered valid. Although the first section of the escalation should be more than enough to invalidate this issue I have added some additional remarks. The protocol can be deployed on L2(and most probably will be),  and if it is to be deployed on mainnet, the auction creator has the ability to set a min bid percent, so he can avoid having a lot of bids if he set it at 10%, and thus the incentives for someone to call the decrypt function are there as well as much lower gas consumed, due to the number of bids.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@AtanasDimulski This is a bit of a unique scenario, where the protocol has acknowledge the risk, and has mentioned the possibility of high number of bids for certain auctions being encouraged as per [comment here](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/237#issuecomment-2041450204). 

Although I am inclined to agree with you, I believe this issue has shown how the usual "gas optimization" issue can have a impact worthy of reconsidering the code logic within the protocol, especially so when decryption is afaik, encouraged to be performed by any user. This may force the protocol to always be the one decrypting, which causes the extensive gas fees here for auctions with such high number of bids, and especially more of a problem if gas fees exceeds the amount of proceeds available to be claimed.

But yes TLDR I can agree that this can be invalid based on sherlock rules given as long as the protocol is willing to pay high gas fees, no auction will be bricked.

**Comment by AtanasDimulski** [comment]
@nevillehuang I agree the watson has reported a valid concern regarding the cost to execute the decryption, however as per this [comment](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/117#issuecomment-2038560497) the sponsor has stated that it is more of a heads up than an actual issue. Gas optimizations are accepted only in C4 and there is a separate report for that, such an issue shouldn't be considered a valid medium. I agree with your TLDR, just wanted to iterate a bit more about why I don't think this is a valid medium issue.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Axis-Fi/moonraker/pull/137

**Comment by kosedogus** [comment]
I agree with @nevillehuang comments in general. But I have some additional things to say:
1. As mentioned by multiple times, this is not a gas optimization report. I explicitly stated that more than once I believe. There are funds at risk, and there will be loss of funds as mentioned by me and also by lead judge above.
2. Axis is an auction platform. It has no purpose to decrypt every auction sellers' auction. Auctions won't be decrypted by protocol, it will be decrypted by auction participants, [here](https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/design/EMPA.md#auction-settlement-part-1-decryption) you can read more about the process.

> and if it is to be deployed on mainnet, the auction creator has the ability to set a min bid percent, so he can avoid having a lot of bids if he set it at 10%, and thus the incentives for someone to call the decrypt function are there as well as much lower gas consumed, due to the number of bids.
3. Not if, yes, it will be deployed to mainnet according to docs, so mainnet is in scope regardless of the current situation of the protocol. And it brings no value for this submission to suggest for auction creators to set a min percent %10 such that there will be only at most 10 bids since Axis is expected to handle thousands of bids. So what you are proposing is: "some of the auctions won't stuck". Yes, but there will also be lots of auctions that will stuck at decryption phase. If all auctions would stuck no matter what, I would have submit it as high, not medium.
(By stuck I refer to auctions that decryption price is more than total funds in the auction. But of course even if it is not more than total funds, we again have loss of funds)

**Comment by Evert0x** [comment]
> In this scenario which has 1510 bids, the gas cost of decryption reached 101 million, hence it needs to be decrypted in at least 4 blocks. The cost of this decryption with 40 gwei gas price is = $14_000 (imagine it during a bullish market season).

Failure to cover this decryption cost would result in all funds being trapped within the contract. Since there is no way to change the state of the auction once it has concluded, except through decryption, funds cannot be moved.

@kosedogus can you provide some more details on this scenario.

I assume 1510 bids are a transaction per bid, correct?
What is the potential & value of the funds being trapped in this scenario? What does it depend on?

**Comment by kosedogus** [comment]
@Evert0x Sure, when the auction is finished, it needs to be settled. Settlement contains two action in order: decrypt() and settle() calls. If decrypt() isn't called, there is no way to retrieve funds back or send the auction results to buyer/seller, so funds will be stuck in this scenario. Every bid is one transaction made for auction to buy the auctioned token. The detailed potential and its dependence is following:
I gave 2 examples in the submission, one auction with 100 bids which requires $1000 to decrypt in the time of submission, and one auction with 1510 bids which requires $14000 to decrypt in the time of submission (which both can be much more as explained). So it seems like with the eth price at the time of submission and gas price given we can more or less say every bid adds $10 to decryption cost. Like explained in the scenario auctions expected to decrypted by auction participants in batches or at once. They specifially mentioned if decryption does not fit into one block, it can be decrypted in more than one block. So it depends on three things:
1. Eth price and gas price (which will make decryption more costly)
2. How many bids are there for the auction (For every additional bids, decryption costs more)
3. How big those bids are (This is only important in terms of incentive which I will explain below)

So let's say we have 1_000 bids and decryption cost is $10_000. Now I will show 4 different scenarios with 2 different potential outcomes:
1. Bids are so big that the maximum bid amount from one person reaches $10_000_000. In that case that person will surely want to decrypt the auction all himself/herself. He/she will lose $10_000.
2. Some people's bids are in the range of $10 to $5_000, these people don't have any incentive to decrypt. But some people's bids are more than $50_000. The latter group agreed to decrypt %10 of the bids each so that they can share the burden of paying $1000 in order to retrieve their $50_000. In this scenario latter group lose funds because they want to at least recover their rest of the funds.
3. Nearly all bids are in the range of $5 to $50. No one has any incentive to decrypt since it means important percentage of fund loss for anyone.
4. Total bid amount is less than $10_000. So it is literally pointless to decrypt, it is definite fund loss.

As you can see even in the best cases, some people will lose funds while some people don't. In the worst cases funds will be stuck and no one will retrieve anything.

**Comment by AtanasDimulski** [comment]
@Evert0x I find it hard to believe that this issue is considered to be something other than gas optimization. If so pretty much all transactions where a user tries to withdraw $50 from a protocol should be considered vulnerable in a bull market. In the extremely unlikely scenario, this issue is not considered a gas optimization issue and is thus invalidated, this falls either in a design decision or in an opportunity loss category, and according to sherlock rules those are not considered valid. It will be extremely unfair to all other wardens, for rules to be changed after the contest has ended and start accepting gas optimization issues as medium issues. No matter how hard the warden tries to spin it, this is clearly a gas optimization as there is no DOS possible.

**Comment by 10xhash** [comment]
> The protocol team fixed this issue in the following PRs/commits: [Axis-Fi/moonraker#137](https://github.com/Axis-Fi/moonraker/pull/137)

Fixed
The implementation is changed from heap to linked list to reduce the gas cost

**Comment by sherlock-admin4** [comment]
The Lead Senior Watson signed off on the fix.

**Comment by Evert0x** [comment]
I believe it's a design choice of the protocol team to grow the decryption costs linearly with the number of bids. It's true that this can cause a mismatch in economic incentives. My judgment is that report informs the protocol team about certain environments where the economic incentives are less strong. Not a medium issue. 

Planning to accept escalation and invalidate issue.

**Comment by kosedogus** [comment]
@Evert0x I am ok with where you think it fits sir but I want to ask some questions to understand the reasoning better. Because I do understand Sherlock has some rules, and I indeed am trying to follow them, but everything can not be strictly written in just one category I believe. I am trying to share my reasoning about why this issue should be considered as valid but I believe escalator just tries some provocative actions if I am not mistaken. So I won't try to answer that comment. Finally, after reading the following questions, if you still think same about the submission. I don't have anything more to add sir. I would appreciate if you can answer them though. Thank you:

You asked about the potential value of the funds being stucked, and what does it depend before. Which answer would make this issue a valid medium?

If a "design choice" leads to stucked funds, is it still not a valid issue? If you say it doesn't lead to direct loss of funds, and they can be recovered by paying for decryption, then I need to ask : by whom and why?

Is it really appropriate to say "funds are not stuck"  if the decryption cost is more than sum of all assets in the auction?

And finally, if the sponsor didn't wrote [this](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/117#issuecomment-2038560497) and say "we don't deploy this part of the codebase to mainnet, we forgot to mention before." Would this conversation be different?

**Comment by AtanasDimulski** [comment]
@kosedogus The lack of valid counterpoints to the arguments I have presented doesn't make them provocative. The issue you have described can fall into three categories - gas optimizations, design decisions, or opportunity loss, all invalid per [Sherlock rules](https://docs.sherlock.xyz/audits/judging/judging). The issue you are describing doesn't lead to any stuck funds, not a single WEI, there is no DOS possible. As for your second question, stuck funds are funds that can't be retrieved, this is clearly not the case here. Finally,  it is evident that the judges didn't find the sponsor's comment you are referring to as a good enough reason to invalidate this issue, otherwise, we wouldn't be having this lengthy discussion.

**Comment by kosedogus** [comment]
> @kosedogus The lack of valid counterpoints to the arguments I have presented doesn't make them provocative

Which arguments?

There is only one possible argument in that comment I can see, which basically trying to put the following two to the same category:
- Someone trying to withdraw their funds from a market, he/she needs to pay gas fees for her/his transaction.
- Someone trying to finish the auction to get their funds from auction, he/she needs to pay not just for his/her, but **everyone's decryption cost**.

Which is a fallacy more than an argument I believe.

Other than that all message is full with fallacies and provocativeness such as:
*In the extremely unlikely scenario, this issue is not considered a gas optimization issue and is thus invalidated*
Which basically suggest there is no other option, either this or that. Which both options is against me.
*It will be extremely unfair to all other wardens, for rules to be changed after the contest has ended and start accepting gas optimization issues*
In here, you are using nearly exact sentence you used twice before without adding any new context.
*No matter how hard the warden tries to spin it*
This, I don't even want to say anything about it :) I am just trying to respond to questions that asked to me with as respectfully as I can be, it is not so hard to do that I believe, you should try it sometimes.

I have no problem with your **arguments**, we are here to discuss. I have been responding every question that asked to me as clear as possible only with arguments and examples when it fits. You are here trying to answer everything even if it is not asked to you. Judge asked a question to me and you are responding in the same time with me with only repetition without providing any new information to discussion. I am asking a question to judge, and you are again here trying to respond. 

You might be right, I might be right, I don't really care about it right now. Just stay calm, and respond when it is necessary with as clear as you can be. It shouldn't be that hard.

But of course since you already wrote some things about my questions I don't want to ignore them: I am aware all the things you are saying, thats why I asked those questions, you are saying there is no stuck funds even one single wei, and that is what I also explained and asked in the exact next line, if we don't count this as a stuck funds, than how we expect those funds to be retrieved, by whom and why? If retrieving those funds means throwing money away to the garbage, how can we classify this problem? Since everyone is trying to classify everything into one of the bug categories, I am just asking is it really fair when problems it create this big, bug should be invalidated because it should fit into one of the categories that is available.

Again, I am not planning to continue with some irrelevant discussion, and I won't answer anything further if it is not directly related to submission and if it can not provide new information. I have asked some questions to judge, not to you, but since you tried to answer them, I appreciated it but I want to hear what Sherlock really think about these kind of situations, I don't want to create some new random discussion. So, will continue to wait for judge's answer if judge think it is fair to answer. Either way I will respect to judge's decision.

**Comment by ArnieSec** [comment]
Kose, with no bias to either warden, I think what dimulski is saying is true. 

Every tx on the EVM costs gas, just because this one costs more gas, does not make it a bug. If the exact same tx would cost 1 cent, you wouldn't raise the issue because there is no bug here. The high gas cost is what is needed to be paid to implement such decryption on chain which is a feature the protocol strives for. Therefore this is a design choice.

Making the decrypting more gas efficient is simply a gas optimization, which by Sherlock rules is invalid.

Also you are not being very respectful as you claim to be. Anyone has any right to comment on the escalation, and you are being very passive aggressive to other wardens. While I understand your frustration, and do not blame you, I am certain the issue is invalid. Either way, arguments were made on each side and it is now up to the judge to decide its validity.

**Comment by kosedogus** [comment]
Thank you sir, I am not frustrated at all, just started to feel a little irritated with the latest comments because of the reasons I explained above. In my latest comment  my attitude is indeed passive aggressive which is intended because I started to feel like, I am, attacked instead of my issue, but I didn't thought I was passive aggressive before, if that is the expression I gave, sorry about that, might be because I am not perfect with language :')  Will certainly try to do something about it :+1: 

Also thank you for the explanation, I understand what you are saying I believe, the only part where I am thinking is something is strange is related to incentive as I mentioned. Yes of course if the exact same tx would cost 1 cent, it won't be a problem because it is not fair to expect an auction with all bid's total is less than 1 cent, and even if that would be the case then it would be considered as dust amount I believe. And also yes decryption is a costly process and this is what protocol strives for. I am also currently not against the issue to be invalid like I said, I just want to understand some things better if it is going to be considered invalid. For example as we now tx wouldn't cost 1 cent, if there is 100 bids it will cost more or less $1000, if for example total bid amount in this auction is $200, how can we expect this tx to occur, and when it won't occur, what would be the name of this scenario if not "stuck". But of course I am aware this is not "fund stuck" as we are generally using to mean DOS or something in that sense to refer there is no possible way to retrieve funds. Indeed there is a way in mentioned scenario but it basically won't occur with correct reasons.

**Comment by ArnieSec** [comment]
> For example as we now tx wouldn't cost 1 cent, if there is 100 bids it will cost more or less $1000, if for example total bid amount in this auction is $200, how can we expect this tx to occur, and when it won't occur, what would be the name of this scenario if not "stuck". But of course I am aware this is not "fund stuck" as we are generally using to mean DOS or something in that sense to refer there is no possible way to retrieve funds. Indeed there is a way in mentioned scenario but it basically won't occur with correct reasons.

I think the majority of frequent blockchain users know the cost of mainnet. Usually this is evident and the market will simply not use this protocol as much on mainnet, and use it more on L2. But it is a completely sensible for the protocol to offer the service on mainnet just in case a user does wish to use it, in which case it is up to the user to assess gas costs and downsides of using said protocol on mainnet. 

This issue can be observed on mainnet on countless different protocols. I myself have minted nfts, which gas cost was more expensive than the purchase price of the nft. If we know it will cost 1000$ to decrypt 100 bids and we proceed to have 50$ auction on mainnet, that is our problem not the problem of the protocol.

**Comment by kosedogus** [comment]
> If we know it will cost 1000$ to decrypt 100 bids and we proceed to have 50$ auction on mainnet, that is our problem not the problem of the protocol.

I understand it is common sense that gas is expensive in mainnet. But I am not sure how this can be expected to known. In the process of reviewing codebase, I generally assume this kind of things are not known to users and/or protocol beforehand. I mean, if you don't know the decryption of the auction, after it ends, will cost $1000 then you can easily proceed to have $50 auction on mainnet.  It seems counter intuitive to me to assume it will be known to users. Of course if this is what is expected from us and it is how the things work in Sherlock, I can try to reflect it in my audit process. But I am not so sure that this is the case.

**Comment by ArnieSec** [comment]
Ultimately there is no loss of funds here, and no dos. Yes I believe this is a suboptimal outcome but ultimately it is a result of mainnet high gas costs and the amount of gas needed to decrypt.

From Sherlock docs

> Design decisions are not valid issues. Even if the design is suboptimal, but doesn't imply any loss of funds, these issues are considered informational.

Although in the scenario you have described it does cost more to retrieve the funds than the funds actual worth. There is no loss of funds, we are still exchanging gas for funds to be retrieved. The funds in the end will be retrieved. We have spent more monetary value than the value of the funds, but the funds can be retrieved no matter what. So if we follow strict adhere to Sherlock rules, we should come to the result that this issue is not fit to be valid.

In the end although more gas is needed to retrieve funds, we still are able to retrieve funds, therefore there is no loss of funds or a DOS.

**Comment by kosedogus** [comment]
> The funds in the end will be retrieved. We have spent more monetary value than the value of the funds, but the funds can be retrieved no matter what. So if we follow strict adhere to Sherlock rules, we should come to the result that this issue is not fit to be valid.

This is exactly what I am trying to say sir, it can be retrieved, but it won't be retrieved with correct reasons. That's why I asked those questions above, is the way to go from here really just technicality and saying it can be retrieved hence there is no issue, or isn't really saying "it won't be retrieved, hence it is problematic" is more realistic and pragmatic for both side (auditors and protocols).

**Comment by AtanasDimulski** [comment]
@kosedogus As I have said before, try to leave your emotions at the door and be as objective as possible. I haven't personally attacked you or provided any fallacy or provocative arguments. As Arnie has stated before gas is the cost of executing transactions on Ethereum, sometimes you may pay $1000 in gas fees to mint an NFT that costs $100, with the hope of it going 100x. This is implied here as well. In all your arguments you calculate the price as is, but forget to mention that users buy crypto tokens with the hope of them going 10x, whether that happens or not is not the point. This falls into the opportunity costs category. Clearly, the main purpose of the protocol is to have encrypted bid auctions, hence design decision. Again whether this is optimal or not is not the point. Finally, this is not the place to discuss Sherlock rules, we follow them as they are in the beginning of the contest.

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

--

The last comment reflects my stance.

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [AtanasDimulski](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/117/#issuecomment-2047122886): accepted
