### ISSUE TITLE
irresponsible - Claiming token yield for weth and usdb will be DOSed for 30 days

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-03-axis-finance-judging#27]
irresponsible

high

# Claiming token yield for weth and usdb will be DOSed for 30 days

## Summary
Claiming token yield for weth and usdb will be DOSed for 30 days
## Vulnerability Detail
In the `BlastAuctionHouse.sol` contract, we can claim yields of gas, weth, and usdb in a single function
(shown below)
```solidity
    function claimYieldAndGas() external {
        // Claim the yield for the WETH and USDB tokens and send to protocol
        _WETH.claim(_protocol, _WETH.getClaimableAmount(address(this)));
        _USDB.claim(_protocol, _USDB.getClaimableAmount(address(this)));

        // Claim the gas consumed by this contract, send to protocol
        _BLAST.claimMaxGas(address(this), _protocol);
    }
```
The problem occurs because of 2 things
1. the claim of gas and tokens is bundled into 1 function
2. We utitilize claimMaxGas to claim gas yields

Why is this problematic? This is problematic because claimMaxGas only claims gas if the claimrate is fully matured and enough time has passed. According to blast docs, maturity of gas is reached at 30 days.

https://docs.blast.io/building/guides/gas-fees#claiming-gas-fees
> For mainnet, the parameters will be set to a 50% initial claim rate, 30 day maturity period, and 100% final claim rate.

This means that any calls to claimMaxGas before maturity of claimrate will cause a revert. Because claimMaxGas is claimed together in a single function with `_WETH.claim` and` _USDB.claim` , these claims will also need to wait the full 30 days for claimMaxGas when they shouldnt need to.

The result is a DOS of claiming of weth and usdb yield of 30 days.

This means that this is a medium severity issue according to sherlock docs
> The issue causes locking of funds for users for more than a week.

additionally another impact is loss of yield.

since we must wait 30 days to claim usdb and weth yield, that yield will not be creating more yield because we have to wait to claim it. 

for example, if the owner were able to claim every day as intended, then at the end of the month he would have more yield than claiming once at the end of the 30 day wait.

since there is 2 impacts i believe high severity is now justified.
## Impact
DOS of claiming of weth and usdb yield of 30 days.
Loss of yield.
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/cadf331f12b485bac184111cdc9ba1344d9fbf01/moonraker/src/blast/BlastAuctionHouse.sol#L63
## Tool used

Manual Review

## Recommendation
Separate the claiming of the tokens USDB and WETH into a whole new function. This allows the owner to claim their yield without the 30 day dos because of claimMaxGas revert.

**Comment by ArnieSec** [comment]
I believe this issue is valid.

> Invalid, no inconsistency, since it is already explicitly mentioned in external integrations of blast

@nevillehuang you have correctly stated that the blast docs do mention this 30 days dos, however this limitation is specific to claiming gas using `claimMaxGas` . This dos should not happen when claiming USDB or WETH yields. USDB and WETH yields should be able to claimed as soon as they accrue. 

The protocol erroneously bundled the calls to claim USDB and WETH yield with a call to claimMaxGas. This will dos the claiming of  yield for USDB and WETH for 30 days, this is not intended behavior for these token yields. 

Furthermore this will cause the protocol to lose out on potential yield, because now the USDB and WETH yield is forced to rebase monthly instead of daily/ per block as is designed to by blast.

Snippets from the sherlock docs that agree with this issues validity

> nevertheless issues involving opportunity loss may be valid issues (for example, due to a loss of core functionality).

As i have explained above, loss of potential token yield happens because of a loss of the core functionality of claiming yield for weth and usdb, those tokens should be able to be claimed whenever the protocol wants to. This fits the criteria perfectly for issue validity.

> The issue causes locking of funds for users for more than a week.

Above i have also explained how tokens incorrectly receive a 30 day dos, which qualifies this issue to be valid once more.

**Comment by sherlock-admin2** [comment]
> 
> I believe this issue is valid.
> 
> > Invalid, no inconsistency, since it is already explicitly mentioned in external integrations of blast
> 
> @nevillehuang you have correctly stated that the blast docs do mention this 30 days dos, however this limitation is specific to claiming gas using `claimMaxGas` . This dos should not happen when claiming USDB or WETH yields. USDB and WETH yields should be able to claimed as soon as they accrue. 
> 
> The protocol erroneously bundled the calls to claim USDB and WETH yield with a call to claimMaxGas. This will dos the claiming of  yield for USDB and WETH for 30 days, this is not intended behavior for these token yields. 
> 
> Furthermore this will cause the protocol to lose out on potential yield, because now the USDB and WETH yield is forced to rebase monthly instead of daily/ per block as is designed to by blast.
> 
> Snippets from the sherlock docs that agree with this issues validity
> 
> > nevertheless issues involving opportunity loss may be valid issues (for example, due to a loss of core functionality).
> 
> As i have explained above, loss of potential token yield happens because of a loss of the core functionality of claiming yield for weth and usdb, those tokens should be able to be claimed whenever the protocol wants to. This fits the criteria perfectly for issue validity.
> 
> > The issue causes locking of funds for users for more than a week.
> 
> Above i have also explained how tokens incorrectly receive a 30 day dos, which qualifies this issue to be valid once more. 
> 
> 
> 

You've deleted an escalation for this issue.

**Comment by nevillehuang** [comment]
I believe there is no loss of funds here. The supposedly "DoS" here applies to the admin, not users, and if they wait for the full 30 days, yields are still being claimed as expected

**Comment by ArnieSec** [comment]
@nevillehuang ,  an admin (short for administrator) can be considered a user of a system. In computing and information technology, a user is broadly defined as any individual or entity that interacts with a computer system or software to perform tasks or access resources.

Admin is still a user, just a user with elevated privilege.

> The issue causes locking of funds for users for more than a week.

The issue is valid.

Furthermore, a bug that impacts a user is given the same severity if it impacts an admin aswell. For example

> Sherlock is exclusively focused on high and medium-severity findings, as these vulnerabilities will cause a loss of user funds and most materially damage the reputation of the protocols Sherlock seeks to protect.

while here it is stated that sherlock is focused on loss of user funds, sherlock still accepts the loss of funds for the protocol/ admin as valid. 

This therefore should mean since locking of 2 weeks or more for a user results in a valid issue, this means that the locking of admin funds for 2 weeks or more should also result in a valid issue.

**Comment by merlin-up** [comment]
`This means that any calls to claimMaxGas before maturity of claimrate will cause a revert.`
You're wrong. This call won't result in a transaction revert.

1) Per the documentation on "Receiving and claiming gas fees" in the Blast platform for the `claimMaxGas` function:
If you’d like to maximize the amount of gas fees claimed and you’re okay waiting for the fees to mature, then you can use claimMaxGas to guarantee a 100% claim rate. By guaranteeing the claim rate, you may not be able to claim all of your gas fees though. `Any remaining fees after calling this function will remain in the Blast Gas contract for you to claim later.`

2) You can verify in the `Blast.sol` and `Gas.sol` smart contracts that there is no potential DOS, and you can freely call the `claimMaxGas` function whenever you wish.

3) And finally, to approve my assertion:
As of the time of writing, the user with the [address](https://blastscan.io/address/0x689aad3ebe15c2cf54dc31791a1c1cba2c65b6a1) executed the `claimMaxGas` function 17 days ago and 6 days ago to claim gas for the smart contract with [address](https://blastscan.io/address/0xc96a98c8c95a0F64A60D9925220D54d28BfE2441) on Blast chain. (The difference in days between the executions of the `claimMaxGas` function is 11).
17 days ago [transaction](https://blastscan.io/tx/0x12aa806602bdb3ead1bdc2a71467530365418a0b9f97d3b4a5d281d8daaa361b):  claimMaxGas(0xc96a98c8c95a0F64A60D9925220D54d28BfE2441,0xc96a98c8c95a0F64A60D9925220D54d28BfE2441)
6 days ago [transaction](https://blastscan.io/tx/0xaf24b2444b0ed8bbab3f5ed1da0ae971e23ec769a59d69567630189879925555):
claimMaxGas(0xc96a98c8c95a0F64A60D9925220D54d28BfE2441,0x689aAd3EbE15c2Cf54DC31791A1c1cbA2C65b6A1)


Therefore, the issue should be considered invalid.

**Comment by ArnieSec** [comment]
> `This means that any calls to claimMaxGas before maturity of claimrate will cause a revert.`
> 
> You're wrong. This call won't result in a transaction revert.
> 
> 
> 
> 1) Per the documentation on "Receiving and claiming gas fees" in the Blast platform for the `claimMaxGas` function:
> 
> If you’d like to maximize the amount of gas fees claimed and you’re okay waiting for the fees to mature, then you can use claimMaxGas to guarantee a 100% claim rate. By guaranteeing the claim rate, you may not be able to claim all of your gas fees though. `Any remaining fees after calling this function will remain in the Blast Gas contract for you to claim later.`
> 
> 
> 
> 2) You can verify in the `Blast.sol` and `Gas.sol` smart contracts that there is no potential DOS, and you can freely call the `claimMaxGas` function whenever you wish.
> 
> 
> 
> 3) And finally, to approve my assertion:
> 
> As of the time of writing, the user with the [address](https://blastscan.io/address/0x689aad3ebe15c2cf54dc31791a1c1cba2c65b6a1) executed the `claimMaxGas` function 17 days ago and 6 days ago to claim gas for the smart contract with [address](https://blastscan.io/address/0xc96a98c8c95a0F64A60D9925220D54d28BfE2441) on Blast chain. (The difference in days between the executions of the `claimMaxGas` function is 11).
> 
> 17 days ago [transaction](https://blastscan.io/tx/0x12aa806602bdb3ead1bdc2a71467530365418a0b9f97d3b4a5d281d8daaa361b):  claimMaxGas(0xc96a98c8c95a0F64A60D9925220D54d28BfE2441,0xc96a98c8c95a0F64A60D9925220D54d28BfE2441)
> 
> 6 days ago [transaction](https://blastscan.io/tx/0xaf24b2444b0ed8bbab3f5ed1da0ae971e23ec769a59d69567630189879925555):
> 
> claimMaxGas(0xc96a98c8c95a0F64A60D9925220D54d28BfE2441,0x689aAd3EbE15c2Cf54DC31791A1c1cbA2C65b6A1)
> 
> 
> 
> 
> 
> Therefore, the issue should be considered invalid.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

You're observation is incorrect

3) your third point doesn't keep into consideration that the user had gas maturing from previous unclaimed yield. It is possible the user had some tx and gas yield that was at 18 day maturation before and after the 17 days, said maturity was realized. This doesn't disprove that on deployment, the contract will have 0 gas positions with 0 maturity and therefore must wait for their first gas tx to mature fully which does infact imply a 30 day dos.

1), 2) this is incorrect aswell, 


uint256 bipsDiff = minClaimRateBips - baseClaimRate;
        uint256 secondsDiff = ceilGasSeconds - baseGasSeconds;
        uint256 rateDiff = ceilClaimRate - baseClaimRate;
        uint256 minSecondsStaked = baseGasSeconds + Math.ceilDiv(bipsDiff * secondsDiff, rateDiff);
        uint256 maxEtherClaimable = etherSeconds / minSecondsStaked;
        if (maxEtherClaimable > etherBalance)  {
            maxEtherClaimable = etherBalance;
        }
        uint256 secondsToConsume = maxEtherClaimable * minSecondsStaked;
        return claim(contractAddress, recipientOfGas, maxEtherClaimable, secondsToConsume);

'''
Above is calculations that are made, inputting the maxClaimRate, we would get a maxEtherclaimable of 0 if we are not yet at full maturity.

At the end of the function we call claim with maxEtherClaimable of 0

Inside the claim function we encounter this require statement.

require(gasToClaim > 0, "must withdraw non-zero amount");

This will cause the call to revert. Therefore my analysis stays correct.

**Comment by ArnieSec** [comment]
@Soloviy for even more clarification to fill any gaps in knowledge about using claimMaxGas. Txs mature individually so if we have 1 tx per day this means that after 30 days. Only one of our tx will have matured fully. The rest are then saved and not claimed until they mature. This explains why only after 17 days the user was able to call claimMaxGas and it succeeded.

Furthermore this advantage is not present at deployment, at deployment the highest maturity gas position is 0 and we must wait for the very first gas position is at full maturity before we can call claimMaxGas, this does result in a 30 day dos for claiming usdb and WETH yield, which should not be subjugated to this 30 day dos.

From blast docs 

> You can think of each transaction’s gas fees as having their own claim rate that evolves independently. As an example, suppose you have 1 ETH in fees from January 1st and 1 ETH in fees from January 15th. When you claim 1 month later on February 1st, you’ll be able to claim 100% of your January 1st fees.

claimMaxGas only claims the gas if the claim rate is at 100%. Since each claim rate evolves individually this furthermore confirms the validity of my issue. The 30 day dos will happen. This dos is acceptable for gas, but this dos shouldn't be applied to USDB and WETH, currently in the protocol this is the case, this is an erroneous implementation. Sherlock states that locking of funds for more than 2 weeks constitutes a valid issue.

**Comment by merlin-up** [comment]
I won't elaborate on why this issue is invalid, as you haven't provided any POC. If you had, you would have realized that the issue is not valid, and there wouldn't be any DOS.

Just also consider this:
1. `etherSeconds = etherSeconds + etherBalance * (block.timestamp - lastUpdated)`;

2. Another example with transactions:
- Contract creation with `0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913` at `Feb-27-2024 08:27:13 PM +UTC`. 
- `Feb-27-2024 11:14:35 PM` +UTC [transaction](https://blastscan.io/tx/0x422d28310804f40e7a7cbbb376de1a0a424b5f575ffdeab3089cc61f97acfd6d): claimMaxGas(0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913,0xD5A7302019040Caa380698fF3a5e7b617c7D8fDd)
- `Feb-27-2024 11:39:37 PM` +UTC [transaction](https://blastscan.io/tx/0x8a11c33158622777b46acd850072edd4a5dbb0aadbbe6f67ab0fa80516c0a42c): claimMaxGas(0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913,0xB5Fbaf79959606E6eb265A9c466010487B30AAad)

In four hours, a new contract is created, and the `claimMaxGas` function is called twice for this contract, which directly contradicts your statements.

**Comment by ArnieSec** [comment]
> I won't elaborate on why this issue is invalid, as you haven't provided any POC. If you had, you would have realized that the issue is not valid, and there wouldn't be any DOS.
> 
> 
> 
> Just also consider this:
> 
> 1. `etherSeconds = etherSeconds + etherBalance * (block.timestamp - lastUpdated)`;
> 
> 
> 
> 2. Another example with transactions:
> 
> - Contract creation with `0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913` at `Feb-27-2024 08:27:13 PM +UTC`. 
> 
> - `Feb-27-2024 11:14:35 PM` +UTC [transaction](https://blastscan.io/tx/0x422d28310804f40e7a7cbbb376de1a0a424b5f575ffdeab3089cc61f97acfd6d): claimMaxGas(0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913,0xD5A7302019040Caa380698fF3a5e7b617c7D8fDd)
> 
> - `Feb-27-2024 11:39:37 PM` +UTC [transaction](https://blastscan.io/tx/0x8a11c33158622777b46acd850072edd4a5dbb0aadbbe6f67ab0fa80516c0a42c): claimMaxGas(0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913,0xB5Fbaf79959606E6eb265A9c466010487B30AAad)
> 
> 
> 
> In four hours, a new contract is created, and the `claimMaxGas` function is called twice for this contract, which directly contradicts your statements.

Once again your lack of understanding is causing you to make erroneous judgements. If you took a closer look at both tx you linked, you would see that both tx the contract claims for another contract not itself. The contracts which had its gas yield claimed did in fact reach maturity. The claim you make that a contract upon deployment can call claimMaxGas is wrong, yes it can claimMaxGas for other contracts but not for itself, or any contract whose gas has not reached full maturity. It is not good to try to invalidate a submission with flawed logic.

**Comment by merlin-up** [comment]
This is my final message, and I am 100% certain that the lack of understanding is on your end.

Three hours after the contract was deployed:
First transaction: caller - `0xd5a7302019040caa380698ff3a5e7b617c7d8fdd`, contractAddress - `0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913`, recipientOfGas - `0xD5A7302019040Caa380698fF3a5e7b617c7D8fDd`
Second transaction: caller - `0xd5a7302019040caa380698ff3a5e7b617c7d8fdd`, contractAddress - `0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913`, recipientOfGas - `0xB5Fbaf79959606E6eb265A9c466010487B30AAad`

The only difference between the two transactions is the recipientOfGas.

Good luck.

**Comment by ArnieSec** [comment]
> This is my final message, and I am 100% certain that the lack of understanding is on your end.
> 
> 
> 
> Three hours after the contract was deployed:
> 
> First transaction: caller - `0xd5a7302019040caa380698ff3a5e7b617c7d8fdd`, contractAddress - `0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913`, recipientOfGas - `0xD5A7302019040Caa380698fF3a5e7b617c7D8fDd`
> 
> Second transaction: caller - `0xd5a7302019040caa380698ff3a5e7b617c7d8fdd`, contractAddress - `0x5330B000925Cd7b5e5d5eb3D3822F13f869f4913`, recipientOfGas - `0xB5Fbaf79959606E6eb265A9c466010487B30AAad`
> 
> 
> 
> The only difference between the two transactions is the recipientOfGas.
> 
> 
> 
> Good luck.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

My apologies, I see your points now you are right. Will remove the escalation, thanks for explanation even when I was being arrogant 👍
