### ISSUE TITLE
seeques - BlastAuctionHouse contract has wrong WETH and USDB addresses as immutables which leads to lost yield

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-03-axis-finance-judging#91]
seeques

medium

# BlastAuctionHouse contract has wrong WETH and USDB addresses as immutables which leads to lost yield

## Summary
The `BlastAuctionHouse` contract has WETH and USDB addresses as constants assigned to the WETH and USDB testnet addresses. In blast developer documentation:
```solidity
contract MyContract {
  // NOTE: these addresses differ on the Blast mainnet and testnet; the lines below are the mainnet addresses
  IERC20Rebasing public constant USDB = IERC20Rebasing(0x4300000000000000000000000000000000000003);
  IERC20Rebasing public constant WETH = IERC20Rebasing(0x4300000000000000000000000000000000000004);
  // NOTE: the commented lines below are the testnet addresses
  // IERC20Rebasing public constant USDB = IERC20Rebasing(0x4200000000000000000000000000000000000022);
  // IERC20Rebasing public constant WETH = IERC20Rebasing(0x4200000000000000000000000000000000000023);
```
In the `BlastAuctionHouse` contract:
```solidity
    /// @notice    Blast contract for claiming gas fees
    IBlast internal constant _BLAST = IBlast(0x4300000000000000000000000000000000000002);

    /// @notice    Address of the WETH contract on Blast
    IERC20Rebasing internal constant _WETH =
        IERC20Rebasing(0x4200000000000000000000000000000000000023); //@audit this is a testnet addresses
        
    /// @notice    Address of the USDB contract on Blast
    IERC20Rebasing internal constant _USDB =
        IERC20Rebasing(0x4200000000000000000000000000000000000022); //@audit

```
This may result in unexpected behavior in smart contracts. If the constructor wouldn't revert, then at worst the yield for WETH and USDB would be lost.
## Vulnerability Detail
See summary
## Impact
DoS of contract creation or lost yield
## Code Snippet
https://github.com/sherlock-audit/2024-03-axis-finance/blob/main/moonraker/src/blast/BlastAuctionHouse.sol#L32-L44
## Tool used

Manual Review

## Recommendation
Check for the correct addresses at:
https://docs.blast.io/building/guides/weth-yield

**Comment by Oighty** [comment]
Duplicate of #73

**Comment by kosedogus** [comment]
Escalate

Isn't deployment reverts because constructor calls `configure()` functions in these addresses which does not exist? When it reverts, it will be understood that something is wrong and will be deployed with correct addresses eventually.
Correct me if I am missing something please, but this doesn't seems like it has any impact if I am right.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Isn't deployment reverts because constructor calls `configure()` functions in these addresses which does not exist? When it reverts, it will be understood that something is wrong and will be deployed with correct addresses eventually.
> Correct me if I am missing something please, but this doesn't seems like it has any impact if I am right.
>  

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by ADK0010** [comment]
@kosedogus  I think you can read this discord comment by @nevillehuang for better understanding of the issue - "I believe medium severity is appropriate. This is not synonymous to front running initializers, because a non-benign deployment would be DoSed given test net addresses not existing in the main blast network is used. Also no information points to protocol knowing about this in advance" .

**Comment by nevillehuang** [comment]
Your statement here already proves there is a impact that renders the whole deployment of the contract non-functional and therefore useless, which constitute a direct smart contract logic fix. This issue should remain valid

> Isn't deployment reverts because constructor calls configure() functions in these addresses which does not exist? When it reverts, it will be understood that something is wrong and will be deployed with correct addresses eventually.

**Comment by kosedogus** [comment]
I am aware that the solution requires code change (changing address). So it is not like exactly written in front running initializers. But because the contract itself can't be deployed in the end with current configuration, I believe it is fair to escalate such an issue considering these two comments from Czar: [1](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/90#issuecomment-1971198695) [2](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/90#issuecomment-1972940491). Don't have anything more to provide. If I am missing something feel free to correct me please, other than that I will respect to final decision nevertheless.

**Comment by kosedogus** [comment]
I am aware that the solution requires code change (changing address). So it is not exactly same with "front running initializers" part of the Sherlock rules. But because the contract itself can't be deployed in the end with current configuration, I believe it is fair to escalate such an issue considering these two comments from Czar: [1](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/90#issuecomment-1971198695) [2](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/90#issuecomment-1972940491). If I am missing something feel free to correct me please, other than that I don't have anything more to provide because it is more of a discussion regarding Sherlock's rules. So I will respect to final decision of Sherlock regardless.

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in the following PRs/commits:
https://github.com/Axis-Fi/moonraker/pull/144

**Comment by 10xhash** [comment]
> The protocol team fixed this issue in the following PRs/commits: [Axis-Fi/moonraker#144](https://github.com/Axis-Fi/moonraker/pull/144)

FIxed
Now the contract addresses are passed as arguments

**Comment by sherlock-admin4** [comment]
The Lead Senior Watson signed off on the fix.

**Comment by Evert0x** [comment]
I believe these "deployment fail" issues have been judges as low in the past. 

As there are no funds at risk with this issue, planning to accept escalation and invalidate issue.

**Comment by ADK0010** [comment]
@Evert0x I think this is a similar issue where wrong address was used and lead to "deployment failure" and it was judged as Medium .
https://github.com/sherlock-audit/2022-09-notional-judging/issues/32

**Comment by AtanasDimulski** [comment]
> @Evert0x I think this is a similar issue where wrong address was used and lead to "deployment failure" and it was judged as Medium . [sherlock-audit/2022-09-notional-judging#32](https://github.com/sherlock-audit/2022-09-notional-judging/issues/32)

This is a contest from 2022 most recently this type of issues have been judged as low/informational [link](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/90)

**Comment by nevillehuang** [comment]
@Evert0x @AtanasDimulski Can you show me some examples? I thought if the smart contract logic points to a permanent DoS (in this case deployment) and if the fix is within the contract (use of hardcoded immutables) then we can consider it valid (this cannot be fixed by deployment scripts like the issue mentioned above)? Anyway I will respect whatever you say since you decide anyways.

**Comment by Evert0x** [comment]
Result:
Invalid
Has Duplicates

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [kosedogus](https://github.com/sherlock-audit/2024-03-axis-finance-judging/issues/91/#issuecomment-2048277611): accepted
